src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 15)]
    private ?string $ref_emballage = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Client $client = null;

    #[ORM\OneToOne(inversedBy: 'commande')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Catalogue $catalogue = null;

   
    #[ORM\Column(length: 15)]
    private ?string $moyen_paiement = null;

    #[ORM\Column(length: 15)]
    private ?string $nbre_versement = null;

    #[ORM\Column(length: 15)]
    private ?string $etat_commande = null;

    #[ORM\Column(length: 25)]
    private ?string $preuve_paiement = null;

    #[ORM\OneToOne(mappedBy: 'commande')]
    private ?Achat $achat = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column]
    private ?float $montantCommande = null;

    #[ORM\Column(length: 25)]
    private ?string $expedition = null;

    

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRefEmballage(): ?string
    {
        return $this->ref_emballage;
    }

    public function setRefEmballage(string $ref_emballage): static
    {
        $this->ref_emballage = $ref_emballage;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): static
    {
        $this->client = $client;

        return $this;
    }

    public function getCatalogue(): ?Catalogue
    {
        return $this->catalogue;
    }

    public function setCatalogue(Catalogue $catalogue): static
    {
        $this->catalogue = $catalogue;

        return $this;
    }

    public function getAchat(): ?Achat
    {
        return $this->achat;
    }

    public function setAchat(Achat $achat): static
    {
        $this->achat = $achat;

        return $this;
    }

    public function getMoyenPaiement(): ?string
    {
        return $this->moyen_paiement;
    }

    public function setMoyenPaiement(string $moyen_paiement): static
    {
        $this->moyen_paiement = $moyen_paiement;

        return $this;
    }

    public function getNbreVersement(): ?string
    {
        return $this->nbre_versement;
    }

    public function setNbreVersement(string $nbre_versement): static
    {
        $this->nbre_versement = $nbre_versement;

        return $this;
    }

    public function getEtatCommande(): ?string
    {
        return $this->etat_commande;
    }

    public function setEtatCommande(string $etat_commande): static
    {
        $this->etat_commande = $etat_commande;

        return $this;
    }

    public function getPreuvePaiement(): ?string
    {
        return $this->preuve_paiement;
    }

    public function setPreuvePaiement(string $preuve_paiement): static
    {
        $this->preuve_paiement = $preuve_paiement;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getMontantCommande(): ?float
    {
        return $this->montantCommande;
    }

    public function setMontantCommande(float $montantCommande): static
    {
        $this->montantCommande = $montantCommande;

        return $this;
    }

    public function getExpedition(): ?string
    {
        return $this->expedition;
    }

    public function setExpedition(string $expedition): static
    {
        $this->expedition = $expedition;

        return $this;
    }

    

}

src/Controller/CommandeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\CommandeRepository;
use App\Entity\Client;
use App\Entity\Commande;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Catalogue;
use App\Repository\CatalogueRepository;
use App\Repository\ClientRepository;

class CommandeController extends AbstractController
{
    private $commandeRepository;
    private $entityManager;
    private $clientRepository;
    private $catalogueRepository;

    public function __construct(CommandeRepository $commandeRepository, EntityManagerInterface $entityManager, ClientRepository $clientRepository, CatalogueRepository $catalogueRepository)
    {
        $this->commandeRepository = $commandeRepository;
        $this->clientRepository = $clientRepository;
        $this->catalogueRepository = $catalogueRepository;
        $this->entityManager = $entityManager;
    }

    #[Route('/commande', name: 'app_commande')]
    public function showCommande(): Response
    {
        $commandes = $this->commandeRepository->findAll();
        $clients = $this->clientRepository->findAll();
        $catalogues = $this->catalogueRepository->findAll();

        return $this->render('commande/index.html.twig', [
          "commandes" => $commandes,
          "clients" => $clients,
          "catalogues" => $catalogues
        ]);
    }

    #[Route('/commande/create', name: 'app_createCommande', methods: ['POST'])]
    public function createCommande(Request $request): Response
    {
        // Récupérer les données du formulaire
        $date = new \DateTime($request->request->get('date'));
        $clientId = $request->request->get('client');
        $catalogueId  = $request->request->get('catalogue');
        $refEmballage = $request->request->get('ref_emballage');
        $moyenPaiement = $request->request->get('moyen_paiement');
        $nbreVersement = $request->request->get('nbre_versement');
        $expedition = $request->request->get('expedition');
        $montant = $request->request->get('montant');
        $etatCommande = $request->request->get('etat_commande');

        // Récupérer les entités Client et Catalogue correspondantes à partir de leurs IDs
        $client = $this->entityManager->getRepository(Client::class)->find($clientId);
        $catalogue = $this->entityManager->getRepository(Catalogue::class)->find($catalogueId);

        // Créer une nouvelle instance de Commande
        $commande = new Commande();
        $commande->setDate($date);
        $commande->setClient($client);
        $commande->setCatalogue($catalogue);
        $commande->setRefEmballage($refEmballage);
        $commande->setMoyenPaiement($moyenPaiement);
        $commande->setNbreVersement($nbreVersement);
        $commande->setExpedition($expedition);
        $commande->setMontantCommande($montant);
        $commande->setEtatCommande($etatCommande);

        // Enregistrer la commande
        $this->entityManager->persist($commande);
        $this->entityManager->flush();

        // Rediriger l'utilisateur vers une page de confirmation ou une autre page de votre choix
        return $this->redirectToRoute('app_commande');
    }
}

templates/commande/index.html.twig
{% extends 'base.html.twig' %}

{% block content_layout %}
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Base de Données Clientèle</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Table des Clients</h6>
        </div>
        <div class="row m-4">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalCommande">
                Nouvelle Commande
            </button>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Ref Catalogue</th>
                            <th>Ref Emballage</th>
                            <th>Client</th>
                            <th>Versements</th>
                            <th>Mode Expédition</th>
                            <th>Moyen Paiement</th>
                            <th>Montant Commande</th>
                            <th>Preuve Paiement</th>
                            <th>Etat Commande</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for commande in commandes %}
                        <tr>
                            <td>{{ commande.date }}</td>
                            <td>{{ commande.catalogue.ref }}</td>
                            <td>{{ commande.refEmballage }}</td>
                            <td>{{ commande.client.nomComplet_Client }}</td>
                            <td>{{ commande.nbreVersement }}</td>
                            <td>{{ commande.expedition }}</td>
                            <td>{{ commande.moyenPaiement }}</td>
                            <td>{{ commande.montant }}</td>
                            <td>{{ commande.preuvePaiement }}</td>
                            <td>{{ commande.etatCommande }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<form action="{{ path('app_createCommande') }}" method="POST">
<div class="modal fade" id="modalCommande" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Enregistrement Nouvelle Commande</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
               <div class="form-group">
                 <label for="">Date Commande</label>
                 <input type="date" name="date" id="" class="form-control" placeholder="" aria-describedby="helpId">
                 <br>
                 <label for="client">Client</label>
                                <select class="form-control" name="client" id="client">
                                 {% for client in clients %}
                                  <option value="{{client.id}}">
                                    {{client.NomCompletClient}}
                                  </option>
                                  {% endfor %}
                                </select>
                 <br>        
                 <label for="catalogue">Catalogue</label>
                    <select class="form-control" name="catalogue" id="catalogue">
                        {% for catalogue in catalogues %}
                            <option value="{{ catalogue.id }}">
                                {{ catalogue.ref }}
                            </option>
                        {% endfor %}
                    </select>     

                 <br>      
                <label for="">Mode Expédition</label>
                <select class="form-control" name="expedition" id="expedition">
                                  <option value="dss2487-sea">DSS2487-SEA</option>
                                  <option value="dss2487-air">DSS2487-AIR</option>
                </select> 
                <br>                 
                <label for="">Moyen Paiement</label>
                <select class="form-control" name="moyen_paiement" id="moyen_paiement">
                                  <option value="espece">Espece</option>
                                  <option value="bancaire">Virement Bancaire</option>
                                  <option value="wave">Wave</option>
                                  <option value="om">Orange Money</option>
                                  <option value="free">Free Money</option>
                                  <option value="cheque">Cheque</option>
                </select>   
                <br>  
                <label for="">Montant Commande</label>
                 <input type="number" name="montant" id="" class="form-control" placeholder="Entrer le montant de la commande" aria-describedby="helpId">  
                 <br> 
                    <label class="form-label" for="customFile">Preuve Paiement</label>
                    <input type="file" class="form-control" id="customFile" />   
                <br>  
                <label for="">Etat Commande</label>
                <select class="form-control" name="etat_commande" id="etat_commande">
                                  <option value="enregistre">Enregistré</option>
                                  <option value="non enregistre">Non Enregistré</option>
                </select>        
               </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Annuler</button>
                <button type="submit" class="btn btn-primary" >Enregistrer</button>
            </div>
        </div>
    </div>
</div>
</form>


{% endblock content_layout %}