src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\DiscriminatorColumn;
use Doctrine\ORM\Mapping\DiscriminatorMap;
use Doctrine\ORM\Mapping\InheritanceType;

#[InheritanceType("JOINED")]
#[DiscriminatorColumn(name:"typeClient", type:"string")]
#[DiscriminatorMap([
    "commercant" => "Commercant" ,
    "particulier" => "Particulier"
])]

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client
{

   

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column] 
    protected ?int $id = null;

    #[ORM\Column(length: 25)]
    protected ?string $emailClient = null;

    #[ORM\Column(length: 25)]
    protected ?string $adresseClient = null;

    #[ORM\ManyToOne(inversedBy: 'clients')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $commercial = null;

    #[ORM\ManyToOne(inversedBy: 'clients')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Reclamations $reclamations = null;



    #[ORM\OneToMany(mappedBy: 'client', targetEntity: Catalogue::class)]
    private Collection $catalogues;

    #[ORM\OneToMany(mappedBy: 'client', targetEntity: Commande::class)]
    private Collection $commandes;

    #[ORM\Column(length: 25)]
    private ?string $nomComplet_Client = null;
    
    #[ORM\Column(length: 25)]
    private ?string $codeClient = null;
  
    /* protected static array $codeCounter = [
        'particulier' => 1,
        'commercant' => 1
    ]; */

    public function __construct()
    {
        $this->catalogues = new ArrayCollection();
        $this->commandes = new ArrayCollection();
        $this->achats = new ArrayCollection();
    }

    public function generateNextCode(): string
    {
        return '';
    }

    


    public function getNomCompletClient(): ?string
    {
        return $this->nomComplet_Client;
    }

    public function setNomCompletClient(string $nomComplet_Client): static
    {
        $this->nomComplet_Client = $nomComplet_Client;

        return $this;
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

   
    #[ORM\OneToMany(mappedBy: 'client', targetEntity: Achat::class)]
    private Collection $achats;

    
 
   

    public function getCodeClient(): ?string
    {
        return $this->codeClient;
    }

    
    public function setCodeClient(string $codeClient): static
    {
        $this->codeClient = $codeClient;

        return $this;
    }


    public function getEmailClient(): ?string
    {
        return $this->emailClient;
    }

    public function setEmailClient(string $emailClient): static
    {
        $this->emailClient = $emailClient;

        return $this;
    }

    public function getAdresseClient(): ?string
    {
        return $this->adresseClient;
    }

    public function setAdresseClient(string $adresseClient): static
    {
        $this->adresseClient = $adresseClient;

        return $this;
    }

    public function getCommercial(): ?User
    {
        return $this->commercial;
    }

    public function setCommercial(?User $commercial): static
    {
        $this->commercial = $commercial;

        return $this;
    }

    public function getReclamations(): ?Reclamations
    {
        return $this->reclamations;
    }

    public function setReclamations(?Reclamations $reclamations): static
    {
        $this->reclamations = $reclamations;

        return $this;
    }


   

    /**
     * @return Collection<int, Catalogue>
     */
    public function getCatalogues(): Collection
    {
        return $this->catalogues;
    }

    public function addCatalogue(Catalogue $catalogue): static
    {
        if (!$this->catalogues->contains($catalogue)) {
            $this->catalogues->add($catalogue);
            $catalogue->setClient($this);
        }

        return $this;
    }

    public function removeCatalogue(Catalogue $catalogue): static
    {
        if ($this->catalogues->removeElement($catalogue)) {
            // set the owning side to null (unless already changed)
            if ($catalogue->getClient() === $this) {
                $catalogue->setClient(null);
            }
        }

        return $this;
    }

   

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setClient($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getClient() === $this) {
                $commande->setClient(null);
            }
        }

        return $this;
    }

    public function getCommercialNomComplet()
    {
        return $this->commercial->getNomComplet(); 

   }

    /**
     * @return Collection<int, Achat>
     */
    public function getAchats(): Collection
    {
        return $this->achats;
    }

    public function addAchat(Achat $achat): static
    {
        if (!$this->achats->contains($achat)) {
            $this->achats->add($achat);
            $achat->setClient($this);
        }

        return $this;
    }

    public function removeAchat(Achat $achat): static
    {
        if ($this->achats->removeElement($achat)) {
            // set the owning side to null (unless already changed)
            if ($achat->getClient() === $this) {
                $achat->setClient(null);
            }
        }

        return $this;
    }
    public function getTypeClient(): string
    {
        if ($this instanceof Particulier) {
            return 'Particulier';
        } elseif ($this instanceof Commercant) {
            return 'Commercant';
        } else {
            // Gérer le cas où le type de client n'est pas reconnu
            return 'Inconnu';
        }
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\Particulier;
use App\Entity\Commercant;
use App\Repository\ClientRepository;
use App\Repository\UserRepository;
use App\Service\CodeClientGenerator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;

class DashboardController extends AbstractController
{
    private $entityManager;
    private $clientRepository;
    private $userRepository;
    private $codeClientGenerator;
    

    public function __construct(EntityManagerInterface $entityManager, ClientRepository $clientRepository, UserRepository $userRepository, CodeClientGenerator $codeClientGenerator)
    {
        $this->entityManager = $entityManager;
        $this->clientRepository = $clientRepository;
        $this->userRepository = $userRepository;
        $this->codeClientGenerator = $codeClientGenerator;
    }

    #[Route('/dashboard/createClient', name: 'app_createClient', methods: ['POST'])]
public function createClient(Request $request): Response
{
    // Récupération des données du formulaire
    $nom = $request->request->get('nom');
    $email = $request->request->get('email');
    $adresse = $request->request->get('adresse');
    $commercialId = $request->request->get('commercial');
    $typeClient = $request->request->get('typeClient');

    // Récupération de l'utilisateur commercial en charge
    $commercial = $this->userRepository->find($commercialId);

    
    // Création d'une nouvelle instance de Client
    if ($typeClient === 'particulier') {
        $client = new Particulier();
    } elseif ($typeClient === 'commercant') {
        $client = new Commercant();
    } else {
        // Gérer le cas où le type de client n'est pas reconnu
        throw new \InvalidArgumentException("Type de client non valide : $typeClient");
    }

    $client->setNomCompletClient($nom);
    $client->setEmailClient($email);
    $client->setAdresseClient($adresse);
    $client->setCommercial($commercial); // Association du commercial
    $client->setCodeClient($this->codeClientGenerator->generateCode($typeClient)); // Génération du code client
    // Sauvegarde du client en base de données
    $this->entityManager->persist($client);
    $this->entityManager->flush();

    // Redirection vers une page de confirmation ou une autre page de votre choix
    return $this->redirectToRoute('app_show_dashboard');
}
    #[Route('/dashboard/showClient', name: 'app_show_dashboard', methods: ['GET'])]
    public function show(): Response
    {
        $datas = $this->clientRepository->findAll();
        $users = $this->userRepository->findAll();
        
    
        return $this->render('dashboard/index.html.twig', [
            "datas" => $datas,
            "users" => $users,
            
        ]);
    }
}

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block content_layout %}
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Base de Données Clientèle</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Table des Clients</h6>
        </div>
        <div class="row m-4">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modelId">
                Enregistrer un client
            </button>
            
            <a name="" id="" class="btn btn-primary ml-4" href="https://passport.alibaba.com/icbu_login.htm?return_url=https%3A%2F%2Fi.alibaba.com%2FglobalBuyerIndex.htm%3Fspm%3Da2700.12243863.b170006.d170006.3ac43e5f8vv1Tk"
                role="button">Sourcing Ali Baba</a>
            <a name="" id="" class="btn btn-primary ml-4" href="https://s.1688.com/youyuan/index.htm?tab=imageSearch&imageAddress=&imageId=1303007990561030430&spm=a26352.b28411319.searchbox.paste&imageIdList=1303007990561030430"
                role="button">Sourcing 1688</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Code Client</th>
                            <th>Nom Complet</th>
                            <th>Email</th>
                            <th>Adresse</th>
                            <th>Commercial en Charge</th>
                            <th>Type de Client</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for client in datas %}
                        <tr>
                            <td>{{ client.codeClient }}</td>
                            <td>{{ client.nomCompletClient }}</td>
                            <td>{{ client.emailClient }}</td>
                            <td>{{ client.adresseClient }}</td>
                            <td>{{ client.commercial.nomComplet }}</td>
                            <td>{{ client.getTypeClient() }}</td>
                            <td style="width: 200px;">
                                <a href="#" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#clientDetailsModal{{ client.id }}">Détails</a>
                                <a href="#" class="btn btn-danger btn-sm">Supprimer</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Enregistrement d'un nouveau client</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <form method="POST" action="{{ path('app_createClient') }}">
                        <div class="form-group p-4">
                            <!-- Vos champs de formulaire ici -->
                            <label for="nom">Nom Complet</label>
                            <input type="text" name="nom" class="form-control" placeholder="Entrer le nom du client" aria-describedby="helpId" required>
                            <br>
                            <label for="email">Email</label>
                            <input type="text" name="email" class="form-control" placeholder="xyz@gmail.com" aria-describedby="helpId">
                            <br>
                            <label for="adresse">Adresse</label>
                            <input type="text" name="adresse" class="form-control" placeholder="Entrer l'adresse du client" aria-describedby="helpId">
                            <br>
                            <div class="form-group">
                                <label for="commercial">Commercial en Charge</label>
                                <select class="form-control" name="commercial" id="commercial">
                                    {% for user in users %}
                                    <option value="{{ user.id }}">{{ user.nomComplet }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="typeClient">Type de Client</label>
                                <select class="form-control" name="typeClient" id="typeClient">
                                    {% for type in ['particulier', 'commercant'] %} {# Vous pouvez remplacer ['particulier', 'commercant'] par les valeurs réelles du discriminant #}
                                        <option value="{{ type }}">{{ type }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Annuler</button>
                <button type="submit" class="btn btn-success" name="btnSave" value="save">Enregistrer</button>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock content_layout %}